### ISSUE TITLE
QR code overlapping (Momcode over QR code) 

### ISSUE THREAD

**Issue by drhus** [drhus/MomCode#14]
QR code Model 2 with Level High error correction allows up to 30% damage, we will use that to overlap QR code with Momcode, 

as the following

![](https://ethresear.ch/uploads/default/original/2X/d/de2547435971e9a8aca7c57a836afd78105db3cd.jpeg)

there should be a way to resize 
1) QR code 
2) momcode 
3) reposation momcode like moving right and left up down.. *not exactly but sort of like this https://schlipak.github.io/IdentiHeart/*

**Comment by alexandrtovmach** [comment]
Implemented
