### ISSUE TITLE
add "default" selected list

### ISSUE THREAD

**Issue by drhus** [drhus/MomCode#16]
adding the ability to pick "default" selected list ideally from [Param.js](https://github.com/drhus/MomCode/blob/master/lab/param.js)

I thought it's there already :?
https://github.com/drhus/MomCode/blob/2bea6bc5ebac8bb9f923940e8f7644b288e54dc1/lab/main.js#L7

**Comment by alexandrtovmach** [comment]
Solved

**Comment by drhus** [comment]
we need the "Default list" to be a variable on Param.js similer to "APP_DEFAULT_MODE" and other Parameters, 

I suggest we adding it under the name of `APP_DEFAULT_HEXLIST_NAMES` on Param.js under `const HEXLIST_NAMES =`

**Comment by drhus** [comment]
it seems this default selector works sometimes and sometimes not, try opening it on incognito tab it wouldn't work :/ it works if you refresh and open again on the same browser but not the first time

**Comment by alexandrtovmach** [comment]
Fixed

**Comment by drhus** [comment]
this last solution here broke 1) `?list=` and 2) viewURL ex. https://momcode.io/lab/?mode=HEX&input=5e0c379d81e1c130f3245dd91207c691cb9f1839&hexListV2=XQAAAQBICQAAAAAAAAB2776oE---ru-_ljcELO--qhjvvqfvvovvv6Lvv7LvvpgCU--_ohLvv4_vvp0W776c776ZZ--_s2bvv5xV776-ZRsoF--_qe--vEbvvrLvv4lS776d77-y776H77-C776J776rNe-_mO-_oe--mQkEfAzvvq7vv63vvoFLBAgn776iVGjvvrLvv4g7Qe-_v13vvofvv6MbV---mO-_vGvvvrDvv6Dvv61FbBUQ77-cZu-_iQ5lNVIrG2zvv6Qr776OY1bvvpzvvoTvvrHvvrQX77-Udu-_ku-_o--_jEhVOu-_he-_p--_m---mO-_v2Fj776DUu-_iu-_ihDvvoVe77-lcu--l--_p---ju-_pHFg77-e77-L77-277-WNe-_uXnvv47vvrU877-A776I77-QU--_m3Pvv7Uk77-TeO-_hUfvv67vv5rvv5rvv7rvv7Dvvp4T77-t776s77-E77-6DELvv4rvvpzvvqjvv6zvvq_vv47vvoYmY---sVhxXGYQ776gUG3vv57vv54x776hFWfvvprvv5Hvv54uTGXvv7Hvvqczcu--k3LvvpHvv43vv64g77-E776oGXzvvprvvp9Sdu-_t0Dvvoh6W--_l--_sWfvvrnvvqPvv6Lvv4ENLHDvvrAUQiPvv5Uf77-f77-377-777-1ce-_rXvvv6kJce-_qO--pEJL77-S77-JMO-_iUIq776g77637767NO-_t--_qk1e776J77-LW21eKHDvvqN277-K77--776F77-cde-_jzs_776nIxXvv5jvv4bvv6jvv4jvvr0_776777-z77-ZTe-_pT9J77-X77-4bgxZ776YPVhZ77-cdO--v1Hvv4bvvr1EdQPvvqp-aXnvvqfvv71URnPvvpXvv7vvv4rvvrgA77-t776xYBcKRO-_qBcT77-v77-UG--_jBBRA---phDvv6PvvoLvv5FqRTFY776377-T77-cLkPvvqNm776OFERWfO-_qe--tngxMu--qu-_rgjvv7nvvoAb77-mb---ru--lXVw776t77-Z776wBO-_lu-_i--_gu-_onQv77-I776S77-i77-m7760Be--uA88Hu-_lGfvvrYkLwrvv4t377-077-PJBHvvrAWBO-_kgtt77-DGe--ve--ke-_gG1WVe--vAHvv4oUMSAB77-THu--qO--v---o---m--_ou--vlfvv4tGDu-_qnYXMu--gu-_iwgcAO-_gXnvv69677-7776y77-h77-iVe--je--kTpUce--pDLvvos_77-VWiPvv6rvvorvvqpn77-d77-c77-ba---oO-_se--jQPvv6Dvvr_vvpPvv6fvvoHvv5bvv7fvvorvv6nvvpxL77-G77-q77-4776a776Ofe-_ie-_pu--qmnvv4Vy77-h776i77-lJO-_nE4z776xXl8g77-WIO-_n2VHXO--tVYCewU_Yu-_ju--l---ue-_jGso77-CGO-_hXfvv6Hvv4Ng776A77-n77-4776I77-_cjnvv4rvv7vvvp3vv5zvvpnvvptx776iNe--u---i--_t0Hvvqk2YO-_pu--m--_v--_vu--glDvvp8

**Comment by alexandrtovmach** [comment]
fixed
