### ISSUE TITLE
allow parsing HexList selected from URL

### ISSUE THREAD

**Issue by drhus** [drhus/MomCode#5]
currently, we parse: Mode, input from URL, will need to add the ability to parse "HexList"

**Comment by alexandrtovmach** [comment]
Solved

**Comment by drhus** [comment]
the ?list=[name] is working however, it parse aswell wit both Export URL & View URL it shouldn't be like that

example https://momcode.io/lab/?list=Momcode-209 >> click on Export URL OR View URL it will print URL below with as ?list=Momcode-209&hexListV2= it should be ONLY ?hexListV2=

the *?list=* variable should only be an input but not to be exported with URL or View URL (that would overwrite hexListV2

**Comment by drhus** [comment]
Ooh I see what happen, the function of Export URL & View URL, will simply take the URL as it is and add to it instead, 

We need to add to https://github.com/drhus/MomCode/blob/c80518bf73adf3983a49e562e256cb0aa711b606/lab/main.js#L497

+ `urlObj.searchParams.delete('list');`

as well ass for #generateViewULR https://github.com/drhus/MomCode/blob/c80518bf73adf3983a49e562e256cb0aa711b606/lab/main.js#L508
