### ISSUE TITLE
Characters from Output / Dictionary table appears as small boxes “tofu”

### ISSUE THREAD

**Issue by drhus** [drhus/MomCode#9]
as we're using Unicode for test lab *(eventually a final version can be set to images/svg but at this stage, this isn't an option etc)* the UTF8 Characters from the table & output appears 1) as tofu or 2) differently depending on platform/browser and font-family *test from PC, then from Android or iPhone :(*

Noto Fonts seems to be an interesting project and eventually should allow unified experience across all devices and with all unicode char.

any solution for this? is there a way we can have now a unified experience across all platforms? at least without tofus !

**Comment by kaede28** [comment]
I research the issue and it seems this is a particular problem for iOS. Supposedly Chrome and Firefox work on Windows / Linux and Android.

I found a site that shows the character map of fonts: http://www.fontspace.com/google/noto-sans/38303/charmap. I checked the symbols on iOS Safari and the page seems to render properly.

The ideal solution would be to use SVG. As an alternative, I suggest you choose a subset of symbols that work on iOS. Other platforms should render properly.

**Comment by drhus** [comment]
> The ideal solution would be to use SVG
it's not an option for test-lab unfortunately, the idea behind the test lab is that beta-testers/developer could easily create their own "Encoding Dictionary Proposal" and share that proposal with a link (View URL) so we can discuss the matter toward reaching a final set of characters (Encoding Dictionay) to be the default one.

it's only possible to have SVG when we have final Encoding Dictionary set.

I don't have iOS, so you confirm momcode.io/lab work smoothly with all characters appearing properly fron iOS and iPhone? I've tested it on android and unfortunately many tofu characters :/

**Comment by drhus** [comment]
I found a way around, Font Awesome 💡 while it doesn't support the Unicode as Unicode symbols but it does as Icon font support +4k symbols/icons as classes so the researcher/beta-tester could create his version of "Encoding Dictionary set"with FA classes (instead of Unicode symbols) 

alternatives icon fonts to consider _(non-support Unicode directly, but with a class name, symbols that often the common symbols we probably want constructing the encoder!)_

* Glyphicons
* Ionicons
* Foundation Icon Fonts
* Material Design Icons (by Google) 
and we can search across them directly from https://tagliala.github.io/vectoriconsroundup/ 

both [IcoMoon](https://icomoon.io/), [Fontello](http://fontello.com/) which supports the creating of "custom" font with selected icons.. might be useful to have a lightweight font on a later stage

**Comment by alexandrtovmach** [comment]
After big research I can summarize ― We can't fix tofu issue, at all.

My idea is create dictionary lists only based on 100% crossplatform symbols:
https://tutorialzine.com/2014/12/you-dont-need-icons-here-are-100-unicode-symbols-that-you-can-use
In addition to crossplatform unicode gliphs we can add icon-fonts, like Font Awesome (as you said).

Currently we should deprecate all symbols which are not crossplatformed or we can start using Font Awesome only.

But we should do this as soon as possible because we shouldn't give users/tester ability to create their own lists with not universal gliphs. We should choose approach now, because if we leave it for future it'll be hard to implement...

**Comment by drhus** [comment]
Hi @alexandrtovmach I think it's great we get to a conclusion that we can't fix tofu issue with a single font, and we can only, for now, use the alternative solution as FontAwsome (and/or other Icon Fonts)

that is' fear enough for now, I will make sure on instruction manual i'm creating on how to use for end-user to explain about this, further deprecate this functionality at the code level it would be enough to explicitly specify an Icon Font library to be used (as FontAwsome) on instruction manual ..
